### PR TITLE
I created the source for unite.

### PR DESCRIPTION
**Pull request by alpaca-tc**
Hi, @nhmood !

I created [unite](https://github.com/Shougo/unite.vim) source for watson as following

[Demo](http://gifzo.net/7rIrvZwusc)

If watson outputed result as json, I can do this.
Please implement outputter as json like following :))))

Or, should I implement outputter?

``` json
{
  "result" : [
    {
      "path" : "lib/watson/version.rb",
      "line" : "36",
      "comment" : "Don"t use DEBUG inside Remote class but pull from calling method"s class?",
      "tag" : "review",
    },
    {
      "path" : "lib/watson/version.rb",
      "line" : "37",
      "comment" : "Not sure if this is the best/proper way to do things but it works...",
      "tag" : "review",
    },
    ...
  ]
}
```

### CODE REVIEW

**Comment by alpaca-tc** [comment]
I implemented some formatter(default, json, unite).
Please test it!

---

vim-unite-watson is good!

q9ejhsdqlk
bh6tb6t9vio

https://github.com/alpaca-tc/vim-unite-watson.vim

**Comment by nhmood** [comment]
Most of the changes look great! I just had a few questions in a few places before I merge all the changes :)

**Comment by alpaca-tc** [comment]
I have not tested `--remote bitbucket` yet because I don't have a account for bitbucket.
Please test it! :)

**Pull request merged**
