### PR TITLE
Cleanup and actual #89 fix

### PR DESCRIPTION
**Pull request by hunterboerner**
Sorry @nhmood but it didn't work :(. I have my changes that do work and did some general ruby cleanup for parser.rb (ruby-fy it!)

### CODE REVIEW

**Comment by nhmood** [comment]
@hunterboerner can you pull the latest and then resubmit this pull request. Commit 48b50969e9020b2b230d32ec3868194eebfc32cf converted all tabs to 2 spaces (which is what you had in your code) so that the diff between your pull request and the main branch will show the actual code changes as opposed to the entire file being changed, better for readability. 
Or if you have another suggestion/solution let me know!

**Comment by hunterboerner** [comment]
Good now?

**Comment by nhmood** [comment]
Just finished reading over it :) Looks great, going to merge and push asap.

Quick question (I was going to merge regardless, but I am curious) what does `#noinspection RubyResolve` on L175 mean/do?

**Comment by hunterboerner** [comment]
That just tells intellij to ignore ::Digest:MD5 inspections. It essentially tells you every problem you have that goes against conventions and then lets you auto fix it. Notice the cleanup commit. That was 99% intellij.

**Pull request merged**
