### PR TITLE
added github 2 factor auth support

### PR DESCRIPTION
**Pull request by T-Mac**

### CODE REVIEW

**Comment by alpaca-tc** [comment]
Nice PR :)) :+1: 

I consider that this behavior is better to write to another method :)

**Comment by T-Mac** [comment]
I actually tried to do that, but I know absolutely no ruby and couldn't get it to work :P . So I settled for this quick hack so I could setup Watson.

**Comment by T-Mac** [comment]
Damn mobile site....

**Comment by alpaca-tc** [comment]
i.c :)

I am going to try to do that!

**Comment by alpaca-tc** [comment]
hmmm
I fixed them but I can not merge it to this pull-request. How can I do that?

https://github.com/alpaca-tc/watson-ruby/tree/pr/222

**Comment by T-Mac** [comment]
I'll just close mine since it duplicaes functionality

**Pull request closed without merging**
